- hosts: all
  become: true

  tasks:

    - name: Install Apache2 and PHP for Debian/Ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install httpd and PHP for CentOS
      dnf:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

